### ISSUE TITLE
2D camera lagging behind

### ISSUE THREAD

**Issue by lenny991** [VioletaSaravia/Overmind#3]
Hey. I've been tinkering around with Godot and this asset for today and yesterday. The 2D camera is very laggy on my end. The player's movement isn't the issue, as it is buttery smooth if inspected without the camera following behind. I've tried a bunch of different values for the X damper but haven't quite figured it out yet. Any help is appreciated.

https://github.com/VioletaSaravia/Overmind/assets/84226646/472cab76-87f8-4d87-947b-88d88727bd2a

Here's my X damper
![image](https://github.com/VioletaSaravia/Overmind/assets/84226646/cf9e1ad2-4d3c-4484-86af-763136cc16f2)

**Comment by lenny991** [comment]
Hey I figured it out np the problem wasn't with the asset, it was my camera. If anyone is running into the same issue, try turning your camera's process callback to physics. Noob mistake. 👍 
![image](https://github.com/VioletaSaravia/Overmind/assets/84226646/4d0e2a4c-1ea6-4f89-9578-f962657451d9)

**Comment by VioletaSaravia** [comment]
Hey! I'm glad that solved it, but I should look into it regardless lol. thanks for the report.

**Comment by lenny991** [comment]
> Hey! I'm glad that solved it, but I should look into it regardless lol. thanks for the report.

I think the problem was mainly to do with the camera, and wasn't an issue with the asset at all. Though, I'll gove you any info if you want to look into it more.
